version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/test/

permissions:
  - object: /

hooks:
  BeforeInstall:
    - location: scripts/delete_app.sh
      timeout: 30
  AfterInstall:
    - location: scripts/chown.sh
      timeout: 30
  ApplicationStart:
    - location: scripts/start_app.sh
