version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/test/
file_exists_behavior: OVERWRITE

permissions:
  - object: /

hooks:
  BeforeInstall:
    - location: scripts/delete_app.sh
      timeout: 30
