name: prac1
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: env
        run: |
          touch .env |
          cat << EOF |
          ${{ secrets.DB_HOST }} |
          ${{ secrets.DB_PORT }} |
          ${{ secrets.DB_USER }} |
          ${{ secrets.DB_PW }} |
          ${{ secrets.DB_DB }} |
          ${{ secrets.GOOGLE_CLIENT_ID }} |
          ${{ secrets.GOOGLE_CLIENT_SECRET }} |
          ${{ secrets.GOOGLE_REDIRECT_URL }} |
          >.env

      - name: archive file
        run: tar cvfz ./zoom.tar.gz * .env

      - name: list
        run: ls -la

      - name: cp s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws --version |
          aws s3 ls |
          aws s3 ls s3://hshlab-s3 |
          aws s3 cp ./zoom.tar.gz s3://hshlab-s3/zoom/

      - name: deploy to seoul
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
          AWS_DEFAULT_REGION: ap-northeast-2
        run: aws deploy create-deployment --application-name zoom-from-actions --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name ec2tos3 --s3-location bucket=hshlab-s3,key=zoom/zoom.tar.gz,bundleType=tgz
